export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          niche: string;
          target_audience: string | null;
          brand_voice: string | null;
          follower_goal: number;
          current_followers: number;
          goal_deadline: string | null;
          preferred_platforms: string[];
          default_tone: string;
          timezone: string;
          subscription_tier: string;
          ai_credits_used: number;
          ai_credits_limit: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          niche?: string;
          target_audience?: string | null;
          brand_voice?: string | null;
          follower_goal?: number;
          current_followers?: number;
          goal_deadline?: string | null;
          preferred_platforms?: string[];
          default_tone?: string;
          timezone?: string;
          subscription_tier?: string;
          ai_credits_used?: number;
          ai_credits_limit?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          niche?: string;
          target_audience?: string | null;
          brand_voice?: string | null;
          follower_goal?: number;
          current_followers?: number;
          goal_deadline?: string | null;
          preferred_platforms?: string[];
          default_tone?: string;
          timezone?: string;
          subscription_tier?: string;
          ai_credits_used?: number;
          ai_credits_limit?: number;
          updated_at?: string;
        };
      };
      content: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          content_type: string;
          tone: string;
          body: Json;
          pillar_id: string | null;
          source_idea_id: string | null;
          source_content_id: string | null;
          platform: string;
          character_count: number | null;
          word_count: number | null;
          estimated_duration: number | null;
          status: string;
          scheduled_for: string | null;
          published_at: string | null;
          ai_model: string | null;
          ai_prompt_used: string | null;
          generation_tokens: number | null;
          views: number;
          likes: number;
          comments: number;
          shares: number;
          saves: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          content_type: string;
          tone?: string;
          body: Json;
          pillar_id?: string | null;
          source_idea_id?: string | null;
          source_content_id?: string | null;
          platform: string;
          character_count?: number | null;
          word_count?: number | null;
          estimated_duration?: number | null;
          status?: string;
          scheduled_for?: string | null;
          published_at?: string | null;
          ai_model?: string | null;
          ai_prompt_used?: string | null;
          generation_tokens?: number | null;
          views?: number;
          likes?: number;
          comments?: number;
          shares?: number;
          saves?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          content_type?: string;
          tone?: string;
          body?: Json;
          pillar_id?: string | null;
          source_idea_id?: string | null;
          source_content_id?: string | null;
          platform?: string;
          character_count?: number | null;
          word_count?: number | null;
          estimated_duration?: number | null;
          status?: string;
          scheduled_for?: string | null;
          published_at?: string | null;
          ai_model?: string | null;
          ai_prompt_used?: string | null;
          generation_tokens?: number | null;
          views?: number;
          likes?: number;
          comments?: number;
          shares?: number;
          saves?: number;
          updated_at?: string;
        };
      };
      ideas: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          notes: string | null;
          category: string;
          pillar_id: string | null;
          tags: string[];
          status: string;
          priority: string;
          target_platforms: string[];
          suggested_content_types: string[];
          source: string | null;
          source_url: string | null;
          trend_id: string | null;
          ai_suggestions: Json | null;
          scheduled_for: string | null;
          posted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          notes?: string | null;
          category: string;
          pillar_id?: string | null;
          tags?: string[];
          status?: string;
          priority?: string;
          target_platforms?: string[];
          suggested_content_types?: string[];
          source?: string | null;
          source_url?: string | null;
          trend_id?: string | null;
          ai_suggestions?: Json | null;
          scheduled_for?: string | null;
          posted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          notes?: string | null;
          category?: string;
          pillar_id?: string | null;
          tags?: string[];
          status?: string;
          priority?: string;
          target_platforms?: string[];
          suggested_content_types?: string[];
          source?: string | null;
          source_url?: string | null;
          trend_id?: string | null;
          ai_suggestions?: Json | null;
          scheduled_for?: string | null;
          posted_at?: string | null;
          updated_at?: string;
        };
      };
      calendar_events: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          start_time: string;
          end_time: string | null;
          all_day: boolean;
          content_id: string | null;
          idea_id: string | null;
          platform: string | null;
          content_type: string | null;
          status: string;
          is_recurring: boolean;
          recurrence_rule: string | null;
          parent_event_id: string | null;
          reminder_minutes: number[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          start_time: string;
          end_time?: string | null;
          all_day?: boolean;
          content_id?: string | null;
          idea_id?: string | null;
          platform?: string | null;
          content_type?: string | null;
          status?: string;
          is_recurring?: boolean;
          recurrence_rule?: string | null;
          parent_event_id?: string | null;
          reminder_minutes?: number[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          start_time?: string;
          end_time?: string | null;
          all_day?: boolean;
          content_id?: string | null;
          idea_id?: string | null;
          platform?: string | null;
          content_type?: string | null;
          status?: string;
          is_recurring?: boolean;
          recurrence_rule?: string | null;
          parent_event_id?: string | null;
          reminder_minutes?: number[];
          updated_at?: string;
        };
      };
      content_pillars: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          color: string | null;
          icon: string | null;
          target_percentage: number;
          total_content: number;
          content_this_month: number;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          color?: string | null;
          icon?: string | null;
          target_percentage: number;
          total_content?: number;
          content_this_month?: number;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string | null;
          color?: string | null;
          icon?: string | null;
          target_percentage?: number;
          total_content?: number;
          content_this_month?: number;
          is_active?: boolean;
          sort_order?: number;
          updated_at?: string;
        };
      };
      analytics_daily: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          platform: string;
          followers: number;
          followers_gained: number;
          followers_lost: number;
          total_views: number;
          total_likes: number;
          total_comments: number;
          total_shares: number;
          total_saves: number;
          posts_published: number;
          engagement_rate: number | null;
          avg_views_per_post: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          platform: string;
          followers?: number;
          followers_gained?: number;
          followers_lost?: number;
          total_views?: number;
          total_likes?: number;
          total_comments?: number;
          total_shares?: number;
          total_saves?: number;
          posts_published?: number;
          engagement_rate?: number | null;
          avg_views_per_post?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          platform?: string;
          followers?: number;
          followers_gained?: number;
          followers_lost?: number;
          total_views?: number;
          total_likes?: number;
          total_comments?: number;
          total_shares?: number;
          total_saves?: number;
          posts_published?: number;
          engagement_rate?: number | null;
          avg_views_per_post?: number | null;
        };
      };
      goals: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          metric: string;
          target_value: number;
          current_value: number;
          start_date: string;
          target_date: string;
          status: string;
          achieved_at: string | null;
          milestones: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          metric: string;
          target_value: number;
          current_value?: number;
          start_date: string;
          target_date: string;
          status?: string;
          achieved_at?: string | null;
          milestones?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string | null;
          metric?: string;
          target_value?: number;
          current_value?: number;
          start_date?: string;
          target_date?: string;
          status?: string;
          achieved_at?: string | null;
          milestones?: Json;
          updated_at?: string;
        };
      };
      trends: {
        Row: {
          id: string;
          topic: string;
          source: string;
          volume: number | null;
          velocity: number | null;
          category: string | null;
          is_fitness_related: boolean;
          relevance_score: number | null;
          data: Json | null;
          fetched_at: string;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          topic: string;
          source: string;
          volume?: number | null;
          velocity?: number | null;
          category?: string | null;
          is_fitness_related?: boolean;
          relevance_score?: number | null;
          data?: Json | null;
          fetched_at?: string;
          expires_at?: string | null;
        };
        Update: {
          id?: string;
          topic?: string;
          source?: string;
          volume?: number | null;
          velocity?: number | null;
          category?: string | null;
          is_fitness_related?: boolean;
          relevance_score?: number | null;
          data?: Json | null;
          fetched_at?: string;
          expires_at?: string | null;
        };
      };
      news_articles: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          content: string | null;
          url: string;
          image_url: string | null;
          source_name: string;
          source_id: string | null;
          author: string | null;
          ai_summary: string | null;
          ai_key_points: Json | null;
          ai_content_ideas: Json | null;
          category: string | null;
          tags: string[];
          relevance_score: number | null;
          published_at: string | null;
          fetched_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          content?: string | null;
          url: string;
          image_url?: string | null;
          source_name: string;
          source_id?: string | null;
          author?: string | null;
          ai_summary?: string | null;
          ai_key_points?: Json | null;
          ai_content_ideas?: Json | null;
          category?: string | null;
          tags?: string[];
          relevance_score?: number | null;
          published_at?: string | null;
          fetched_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          content?: string | null;
          url?: string;
          image_url?: string | null;
          source_name?: string;
          source_id?: string | null;
          author?: string | null;
          ai_summary?: string | null;
          ai_key_points?: Json | null;
          ai_content_ideas?: Json | null;
          category?: string | null;
          tags?: string[];
          relevance_score?: number | null;
          published_at?: string | null;
          fetched_at?: string;
        };
      };
      saved_articles: {
        Row: {
          id: string;
          user_id: string;
          article_id: string;
          notes: string | null;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          article_id: string;
          notes?: string | null;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          article_id?: string;
          notes?: string | null;
          is_read?: boolean;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
};
